import { 
  getProducts,
  getProduct,
  addProduct,
  updateProduct,
  deleteProduct,
  getCategories,
  addCategory,
  updateCategory,
  getUsers,
  getUser,
  addUser,
  updateUser,
  getStores,
  getInventoryBatches,
  getSales,
  addSale,
  getClients,
  addClient,
  getTransfers,
  getShoppingList,
  getExpenses,
  getCashClosings,
  initializeSupabaseCollections
} from './supabaseAPI';

// Exportar todas las funciones para mantener la compatibilidad
export {
  getProducts,
  getProduct,
  addProduct,
  updateProduct,
  deleteProduct,
  getCategories,
  addCategory,
  updateCategory,
  getUsers,
  getUser,
  addUser,
  updateUser,
  getStores,
  getInventoryBatches,
  getSales,
  addSale,
  getClients,
  addClient,
  getTransfers,
  getShoppingList,
  getExpenses,
  getCashClosings,
  initializeSupabaseCollections
};